import { test, expect } from './fixture';
test('cycle preferences retain history, memories stay explicit and gentle mode is optional', async ({ page }) => {
 await page.goto('/#Settings'); await page.getByRole('switch', { name: 'Cycle tracking', exact: true }).check(); await page.goto('/#Cycle'); await page.getByRole('button', { name: 'Start period', exact: true }).click(); await expect(page.getByRole('heading', { name: /ongoing/ })).toBeVisible();
 await page.goto('/#Settings'); await page.getByRole('switch', { name: 'Cycle tracking', exact: true }).uncheck(); await page.goto('/#Cycle'); await expect(page.getByText(/Existing history is preserved/)).toBeVisible(); await page.goto('/#Settings'); await page.getByRole('switch', { name: 'Cycle tracking', exact: true }).check(); await page.goto('/#Cycle'); await expect(page.getByRole('heading', { name: /ongoing/ })).toBeVisible();
 await page.goto('/#Today'); await page.getByRole('switch', { name: 'Gentle Mode', exact: true }).check(); await expect(page.getByText("We're doing less today. That's the plan.")).toBeVisible();
 await page.goto('/#What%20this%20app%20knows'); await page.getByRole('textbox', { name: 'About', exact: true }).fill('Food preference'); await page.getByRole('textbox', { name: 'What to remember' }).fill('I like warm breakfast.'); await page.getByRole('button', { name: 'Confirm and remember' }).click(); await expect(page.getByRole('heading', { name: 'Food preference' })).toBeVisible();
});
for (const layout of [{ name: 'small-phone', width: 320, height: 720 }, { name: 'phone', width: 390, height: 844 }, { name: 'tablet-portrait', width: 768, height: 1024 }, { name: 'tablet-landscape', width: 1024, height: 768 }, { name: 'desktop', width: 1440, height: 900 }]) test(`product screens and compact controls: ${layout.name}`, async ({ page }, testInfo) => {
 await page.setViewportSize(layout); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
 for (const screen of ['Today', 'Journal', 'Timeline', 'Cycle', 'Projects', 'Me Time', 'Settings', 'What this app knows', 'Reminders', 'Logs', 'Availability']) { await page.goto(`/#${encodeURIComponent(screen)}`); await expect(page.locator('main')).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: testInfo.outputPath(`${screen.replaceAll(' ', '-')}.png`), fullPage: true }); }
 await page.goto('/#Projects'); await page.getByRole('textbox', { name: 'New task', exact: true }).fill('A very long task name that should wrap nicely even on a small phone and inside a memo'); await page.getByRole('button', { name: 'Add task', exact: true }).click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 const circles = await page.locator('.icon-circle').evaluateAll(nodes => nodes.map(n => { const s = getComputedStyle(n); return { width: parseFloat(s.width), height: parseFloat(s.height), align: s.alignItems, justify: s.justifyContent }; })); expect(circles.length).toBeGreaterThan(0); for (const c of circles) { expect(c.width).toBe(c.height); expect(c.align).toBe('center'); expect(c.justify).toBe('center'); } expect(errors).toEqual([]);
});
