import { useState } from 'react';
import type { CalendarService } from '../services/calendarService';
import { dateKey } from '../services/productService';
import { availability, availabilityText, downloadAvailabilityImage, type AvailabilitySlot } from '../services/availability';
import { Toggle } from './Controls';
export function AvailabilityScreen({ calendar }: { calendar: CalendarService }) {
 const [from, setFrom] = useState(dateKey()); const [to, setTo] = useState(dateKey()); const [start, setStart] = useState(8); const [end, setEnd] = useState(22); const [includeMaybe, setIncludeMaybe] = useState(false); const [maybeStart, setMaybeStart] = useState(''); const [maybeEnd, setMaybeEnd] = useState(''); const [slots, setSlots] = useState<AvailabilitySlot[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
 return <section className="paper-section"><h1>Share a little availability</h1><p>Only FREE, BUSY and MAYBE leave this screen. Nothing is published.</p><form className="entry-form" onSubmit={e => { e.preventDefault(); setSlots([]); setLoading(true); setError(''); void calendar.readRange(from, to).then(events => setSlots(availability(events, from, to, start, end, includeMaybe && maybeStart && maybeEnd ? [{ start: new Date(maybeStart).toISOString(), end: new Date(maybeEnd).toISOString() }] : []))).catch(() => setError('Connect Calendar and check your dates. Availability needs a fresh Calendar read.')).finally(() => setLoading(false)); }}><label>From<input type="date" required value={from} onChange={e => { setFrom(e.target.value); setSlots([]); }} /></label><label>Through<input type="date" required min={from} value={to} onChange={e => { setTo(e.target.value); setSlots([]); }} /></label><label>Start hour<input type="number" min="0" max="23" required value={start} onChange={e => { setStart(Number(e.target.value)); setSlots([]); }} /></label><label>End hour<input type="number" min="1" max="24" required value={end} onChange={e => { setEnd(Number(e.target.value)); setSlots([]); }} /></label><Toggle label="Include a maybe window" checked={includeMaybe} onChange={on => { setIncludeMaybe(on); setSlots([]); }} />{includeMaybe && <><label>Maybe from<input required type="datetime-local" value={maybeStart} onChange={e => { setMaybeStart(e.target.value); setSlots([]); }} /></label><label>Maybe through<input required type="datetime-local" value={maybeEnd} onChange={e => { setMaybeEnd(e.target.value); setSlots([]); }} /></label></>}<button disabled={loading}>Generate private preview</button></form>{error && <p role="status">{error}</p>}{slots.length > 0 && <><pre className="availability-output">{availabilityText(slots)}</pre><button onClick={() => { const blob = new Blob([availabilityText(slots)], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'availability.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>Export text</button><button onClick={() => downloadAvailabilityImage(slots)}>Export image</button></>}<p className="small muted">This view uses your connected primary Calendar. Tasks, actual activities, journals and health information are excluded.</p></section>;
}
