import { useState } from 'react';
import type { Meal, Observation } from '../domain/models';
import { dateKey, localDateTime, type ProductService } from '../services/productService';
import { Pill, Toggle } from './Controls';
export function FoodForm({ product, done }: { product: ProductService; done: () => void }) {
  const [kind, setKind] = useState<Meal['kind']>('lunch'); const [description, setDescription] = useState(''); const [time, setTime] = useState(localDateTime()); const [protein, setProtein] = useState<Meal['protein']>('unsure'); const [fibre, setFibre] = useState<Meal['fibre']>('unsure'); const [notes, setNotes] = useState(''); const [photo, setPhoto] = useState<File>(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  return <form className="entry-form" onSubmit={e => { e.preventDefault(); setSaving(true); void (async () => { const photoId = photo ? await product.savePhoto(photo) : undefined; await product.add('meals', { kind, description: description.trim(), time: new Date(time).toISOString(), protein, fibre, notes, ...(photoId ? { photoId } : {}) }); done(); })().catch(() => setError('Could not save this meal. Check the time and photo.')).finally(() => setSaving(false)); }}><h2>Have you eaten yet?</h2><div className="choices">{(['breakfast', 'lunch', 'dinner', 'snack'] as const).map(k => <Pill key={k} selected={kind === k} onClick={() => setKind(k)}>{k}</Pill>)}</div><label>What did you have?<input required value={description} onChange={e => setDescription(e.target.value)} maxLength={1000} /></label><label>When<input type="datetime-local" required value={time} onChange={e => setTime(e.target.value)} /></label>{[{ title: 'Protein present?', value: protein, change: setProtein }, { title: 'Fibre present?', value: fibre, change: setFibre }].map(scale => <fieldset key={scale.title}><legend>{scale.title}</legend><div className="choices">{(['yes', 'no', 'unsure'] as const).map(v => <Pill key={v} selected={scale.value === v} onClick={() => scale.change(v)}>{v}</Pill>)}</div></fieldset>)}<label>Photo (optional, saved only on this device)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setPhoto(e.target.files?.[0])} /></label><label>Notes / how it felt<textarea value={notes} onChange={e => setNotes(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<button disabled={saving}>Save meal</button><p className="small muted">No calorie estimates. Photos are local and excluded from cloud sync.</p></form>;
}
export function BodyForm({ product, done }: { product: ProductService; done: () => void }) {
  const [energy, setEnergy] = useState<Observation['energy']>(); const [calm, setCalm] = useState<Observation['calm']>(); const [stress, setStress] = useState<Observation['stress']>(); const [mood, setMood] = useState(''); const [body, setBody] = useState(''); const [symptoms, setSymptoms] = useState(''); const [error, setError] = useState('');
  return <form className="entry-form" onSubmit={e => { e.preventDefault(); void product.add('observations', { date: dateKey(), ...(energy ? { energy } : {}), ...(calm ? { calm } : {}), ...(stress ? { stress } : {}), mood, bodyState: body, symptoms: symptoms.split(',').map(s => s.trim()).filter(Boolean) }).then(done).catch(() => setError('Could not save. Please try again.')); }}><h2>How is it feeling?</h2><fieldset><legend>Energy</legend><div className="choices">{(['very-low', 'low', 'steady', 'high'] as const).map(v => <Pill key={v} selected={energy === v} onClick={() => setEnergy(v)}>{v.replace('-', ' ')}</Pill>)}</div></fieldset>{[{ label: 'Calm', value: calm, change: setCalm }, { label: 'Stress', value: stress, change: setStress }].map(scale => <fieldset key={scale.label}><legend>{scale.label}</legend><div className="choices">{(['low', 'steady', 'high'] as const).map(v => <Pill key={v} selected={scale.value === v} onClick={() => scale.change(v)}>{v}</Pill>)}</div></fieldset>)}<label>Mood, in your words<input value={mood} onChange={e => setMood(e.target.value)} maxLength={300} /></label><label>Body / notes<textarea value={body} onChange={e => setBody(e.target.value)} /></label><label>Symptoms (separate with commas)<input value={symptoms} onChange={e => setSymptoms(e.target.value)} placeholder="Headache, cramps, or your own words" /></label>{energy === 'very-low' && <p>Want to make today lighter? Gentle Mode is yours to choose in Today.</p>}{error && <p role="alert">{error}</p>}<button>Save check-in</button></form>;
}
export function CarePanel({ product, data, act, hydrationEnabled }: { product: ProductService; data: Awaited<ReturnType<ProductService['snapshot']>>; act: (f: () => Promise<unknown>) => void; hydrationEnabled: boolean }) {
  const [title, setTitle] = useState(''); const [timeOfDay, setTimeOfDay] = useState<'morning' | 'evening' | 'any'>('any'); const today = dateKey(); const glasses = data.hydration.filter(h => dateKey(new Date(h.time)) === today).reduce((n, h) => n + h.glasses, 0);
  return <section className="care-panel"><h2>A little care</h2>{hydrationEnabled && <div><p>{glasses ? `${glasses} ${glasses === 1 ? 'glass' : 'glasses'} logged today.` : 'Water check.'}</p><button onClick={() => act(() => product.add('hydration', { time: new Date().toISOString(), glasses: 1 }))}>Log a glass</button></div>}{data.careRoutines.filter(r => r.enabled).map(r => { const log = data.careLogs.filter(l => l.routineId === r.id && l.date === today).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]; return <div className="care-item" key={r.id}><strong>{r.title}</strong><div className="choices">{(['done', 'taken', 'skipped', 'not-today'] as const).map(status => <Pill key={status} selected={log?.status === status} onClick={() => act(() => log ? product.update('careLogs', log.id, { status }) : product.add('careLogs', { routineId: r.id, date: today, status }))}>{status.replace('-', ' ')}</Pill>)}</div></div>; })}<details><summary>Edit care routines</summary>{data.careRoutines.map(r => <div key={r.id}><Toggle label={r.title} checked={r.enabled} onChange={enabled => act(() => product.update('careRoutines', r.id, { enabled }))} /><button onClick={() => { const name = prompt('Routine name', r.title); if (name?.trim()) act(() => product.update('careRoutines', r.id, { title: name.trim() })); }}>Rename</button><button onClick={() => { if (confirm('Remove this routine? Recorded completions stay.')) act(() => product.remove('careRoutines', r.id)); }}>Remove</button></div>)}<form onSubmit={e => { e.preventDefault(); act(async () => { await product.add('careRoutines', { title: title.trim(), timeOfDay, enabled: true }); setTitle(''); }); }}><label>New routine<input required value={title} onChange={e => setTitle(e.target.value)} maxLength={140} /></label><label>When<select value={timeOfDay} onChange={e => setTimeOfDay(e.target.value as typeof timeOfDay)}><option value="any">Any time</option><option value="morning">Morning</option><option value="evening">Evening</option></select></label><button>Add routine</button></form></details></section>;
}
