import { useState } from 'react';
import type { Cycle } from '../domain/models';
import { dateKey, type ProductService } from '../services/productService';
import { previewCycleImport } from '../services/cycleImport';
import { Pill } from './Controls';
export function CycleScreen({ records, enabled, product, act }: { records: Cycle[]; enabled: boolean; product: ProductService; act: (f: () => Promise<unknown>) => void }) {
 const [editing, setEditing] = useState<Cycle | null>(null); const [start, setStart] = useState(dateKey()); const [end, setEnd] = useState(''); const [flow, setFlow] = useState<'light' | 'medium' | 'heavy'>('medium'); const [symptoms, setSymptoms] = useState(''); const [notes, setNotes] = useState(''); const [importText, setImportText] = useState(''); const [preview, setPreview] = useState<ReturnType<typeof previewCycleImport>>(); const [error, setError] = useState(''); const [result, setResult] = useState('');
 const clear = () => { setEditing(null); setStart(dateKey()); setEnd(''); setSymptoms(''); setNotes(''); };
 return <section className="paper-section"><p className="eyebrow">Your own rhythm</p><h1>Cycle</h1>{!enabled ? <p>Cycle tracking is hidden from everyday logging. You can enable it in Settings. Existing history is preserved.</p> : <><form className="entry-form" onSubmit={e => { e.preventDefault(); const fields = { periodStart: start, ...(end ? { periodEnd: end } : {}), notes, symptoms: symptoms.split(',').map(s => s.trim()).filter(Boolean), flow: editing ? editing.flow : [{ date: start, level: flow }] }; act(async () => { if (editing) await product.update('cycles', editing.id, fields); else await product.add('cycles', fields); clear(); }); }}><h2>{editing ? 'Edit period' : 'Log a period'}</h2><label>Period started<input type="date" required value={start} onChange={e => setStart(e.target.value)} /></label><label>Period ended (optional)<input type="date" min={start} value={end} onChange={e => setEnd(e.target.value)} /></label>{!editing && <fieldset><legend>Flow on the start date</legend><div className="choices">{(['light', 'medium', 'heavy'] as const).map(v => <Pill key={v} selected={flow === v} onClick={() => setFlow(v)}>{v}</Pill>)}</div></fieldset>}<label>Symptoms (separate with commas)<input value={symptoms} onChange={e => setSymptoms(e.target.value)} /></label><label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} /></label><button>{editing ? 'Save period' : 'Start period'}</button>{editing && <button type="button" onClick={clear}>Cancel</button>}</form>
 {[...records].sort((a, b) => b.periodStart.localeCompare(a.periodStart)).map(c => <article className="cycle-entry" key={c.id}><h3>{c.periodStart}{c.periodEnd ? ` to ${c.periodEnd}` : ' / ongoing'}</h3><p>{c.symptoms.join(', ')}</p><p className="journal-text">{c.notes}</p><div className="choices"><button onClick={() => { setEditing(c); setStart(c.periodStart); setEnd(c.periodEnd ?? ''); setSymptoms(c.symptoms.join(', ')); setNotes(c.notes); }}>Edit</button>{!c.periodEnd && <button onClick={() => act(() => product.update('cycles', c.id, { periodEnd: dateKey() }))}>Period ended today</button>}<button onClick={() => { const date = prompt('Flow date (YYYY-MM-DD)', dateKey()); if (date) { const level = prompt('Flow: light, medium, heavy', 'medium'); if (['light', 'medium', 'heavy'].includes(level ?? '')) act(() => product.update('cycles', c.id, { flow: [...c.flow.filter(f => f.date !== date), { date, level: level as 'light' }] })); } }}>Log flow</button><button onClick={() => { if (confirm('Remove this period record?')) act(() => product.remove('cycles', c.id)); }}>Remove</button></div></article>)}
 <details><summary>Import historical periods</summary><p className="small muted">JSON array: periodStart, optional periodEnd, notes, symptoms, flow. No predictions or 28-day assumptions.</p><label>Choose JSON file<input type="file" accept="application/json,.json" onChange={e => { const f = e.target.files?.[0]; if (f && f.size <= 5_000_000) void f.text().then(text => { setImportText(text); setPreview(undefined); }); else setError('Choose a JSON file smaller than 5 MB.'); }} /></label><label>Or paste JSON<textarea value={importText} onChange={e => { setImportText(e.target.value); setPreview(undefined); }} /></label><button onClick={() => { try { setPreview(previewCycleImport(importText)); setError(''); } catch { setError('Could not read this JSON. Use an array of cycle records.'); } }}>Validate import</button>{error && <p role="alert">{error}</p>}{preview && <><p>Detected: {preview.detected}. Valid: {preview.valid.length}. Rejected: {preview.rejected.length}.<br />{preview.from} to {preview.to}</p>{preview.rejected.length > 0 && <p>Rejected rows: {preview.rejected.join(', ')}</p>}<button disabled={!preview.valid.length} onClick={() => { if (confirm('Import the valid records? Existing history stays. Duplicate start dates will be skipped.')) act(async () => { const n = await product.importCycles(importText); setResult(`${n} periods imported. Original history preserved.`); setPreview(undefined); }); }}>Confirm import</button></>}{result && <p role="status">{result}</p>}</details></>}
 <p className="small muted">This is your record. It does not diagnose symptoms or estimate fertility.</p></section>;
}
