import { useEffect, useRef, useState } from 'react';
import { LineIcon, logKinds, type LogKind } from './HomeScreen';
export function LogSheet({ kind, close, select, navigate }: { kind: LogKind | 'choose'; close: () => void; select: (kind: LogKind) => void; navigate: (screen: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [feelings, setFeelings] = useState<Record<string, string>>({});
  useEffect(() => { dialog.current?.showModal(); return () => { dialog.current?.close(); }; }, []);
  return <dialog ref={dialog} className="log-sheet" onCancel={close} onClick={event => { if (event.target === event.currentTarget) close(); }}><div className="sheet-handle" /><button className="sheet-close" onClick={close} aria-label="Close log">×</button>
    {kind === 'choose' ? <><p className="eyebrow">A moment from your life</p><h2>What are we logging?</h2><div className="log-options">{logKinds.map(option => <button key={option} onClick={() => select(option)}><LineIcon kind={option} /><span>{option}</span><span aria-hidden="true">↗</span></button>)}</div></> : <><span className="prototype-label">Interface prototype · not recording</span><div className="prototype-icon"><LineIcon kind={kind} /></div><h2>{kind === 'Talk' ? 'A little room to talk.' : kind === 'Note' ? 'Whatever’s on your mind.' : kind}</h2><p>{kind === 'Talk' ? 'Voice recording isn’t connected yet. No microphone is active and no audio is saved.' : 'This log form is a preview. Entries here aren’t saved yet.'}</p>
      {kind === 'Body / mood' && <div className="feeling-prototype">{[{ name: 'Energy', values: ['Low', 'Steady', 'High'] }, { name: 'Calm', values: ['Restless', 'Okay', 'Settled'] }, { name: 'Stress', values: ['Low', 'Some', 'High'] }].map(scale => <fieldset key={scale.name}><legend>{scale.name}</legend>{scale.values.map(value => <label className={feelings[scale.name] === value ? 'selected' : ''} key={value}><input type="radio" name={scale.name} value={value} checked={feelings[scale.name] === value} onChange={() => setFeelings(current => ({ ...current, [scale.name]: value }))} /><span>{value}</span></label>)}</fieldset>)}<label className="body-prototype-label">Mood / body<input placeholder="In your own words…" /></label></div>}
      <p className="muted small">Task creation and task timers work now. Other ways to record your day arrive in a later phase.</p><button className="talk-button" onClick={() => select('Task')}>Add a task instead</button><button className="text-link" onClick={() => { close(); navigate('Journal'); }}>Visit your journal ↗</button></>}
  </dialog>;
}
