import { useState } from 'react';
import type { Project, Task } from '../domain/models';
import type { LifeService } from '../services/lifeService';
import type { ProductService } from '../services/productService';
import { AddButton, Pill, Toggle } from './Controls';
import { TaskList } from './TaskList';
type Snapshot = Awaited<ReturnType<LifeService['snapshot']>>;
export function MemoBoard({ data, now, life, product, act, calendarAction, showCompleted, setShowCompleted }: { data: Snapshot; now: number; life: LifeService; product: ProductService; act: (f: () => Promise<unknown>) => void; calendarAction: (t: Task) => void; showCompleted: boolean; setShowCompleted: (on: boolean) => void }) {
  const [kind, setKind] = useState<'Task' | 'Checklist' | 'Project'>('Task');
  const [title, setTitle] = useState(''); const [editing, setEditing] = useState<Project | null>(null);
  const roots = data.tasks.filter(t => !t.parentTaskId && (showCompleted || !t.completed)).sort((a, b) => Number(Boolean(b.pinnedTasks)) - Number(Boolean(a.pinnedTasks)) || (a.sortOrder ?? 0) - (b.sortOrder ?? 0));
  return <section className="paper-section"><p className="eyebrow">Little notes for later</p><h1>Projects &amp; tasks</h1>
    <div className="choices">{(['Task', 'Checklist', 'Project'] as const).map(k => <Pill key={k} selected={kind === k} onClick={() => setKind(k)}>{k}</Pill>)}</div>
    <form className="add-task" onSubmit={e => { e.preventDefault(); act(async () => { if (!title.trim()) return; if (kind === 'Project') await product.add('projects', { title: title.trim(), description: '', notes: '', status: 'active', priority: 'normal' }); else await life.addTask(title, { kind: kind === 'Checklist' ? 'checklist' : 'task' }); setTitle(''); }); }}><label className="sr-only" htmlFor="new-task">New task</label><input id="new-task" required value={title} onChange={e => setTitle(e.target.value)} placeholder="Something to remember..." maxLength={140} /><button type="submit">{kind === 'Project' ? 'Add project' : kind === 'Checklist' ? 'Add checklist' : 'Add task'}</button></form>
    <Toggle label="Show completed tasks" checked={showCompleted} onChange={setShowCompleted} />
    <div className="memo-board">{roots.map(task => <article className="memo-card" key={task.id}>
      <TaskList tasks={[task]} allTasks={data.tasks} activities={data.activities} active={data.active} now={now} life={life} act={act} calendarAction={calendarAction} />
      <details><summary>Memo details</summary><label>Notes<textarea defaultValue={task.notes} onBlur={e => act(() => life.editTask(task.id, { notes: e.target.value }))} /></label><label>Project<select value={task.projectId ?? ''} onChange={e => act(() => life.editTask(task.id, { projectId: e.target.value || undefined }))}><option value="">Life / no project</option>{data.projects.map(p => <option key={p.id} value={p.id}>{p.title} ({p.status})</option>)}</select></label><label>Deadline<input type="date" value={task.deadline ?? ''} onChange={e => act(() => life.editTask(task.id, { deadline: e.target.value || undefined }))} /></label><label>Estimated minutes<input type="number" min="0" value={task.estimatedMinutes ?? ''} onChange={e => act(() => life.editTask(task.id, { estimatedMinutes: e.target.value ? Number(e.target.value) : undefined }))} /></label>
        <Toggle label={`Important: ${task.title}`} checked={task.important} onChange={on => act(() => life.editTask(task.id, { important: on }))} />
        <Toggle label={`Pin to Today: ${task.title}`} checked={Boolean(task.pinnedToday)} onChange={on => act(() => life.editTask(task.id, { pinnedToday: on }))} />
        <Toggle label={`Pin in Tasks: ${task.title}`} checked={Boolean(task.pinnedTasks)} onChange={on => act(() => life.editTask(task.id, { pinnedTasks: on }))} />
        <Toggle label={`Allow home-screen widget: ${task.title}`} checked={Boolean(task.widgetEligible)} onChange={on => act(() => life.editTask(task.id, { widgetEligible: on }))} /><p className="small muted">Only explicitly selected memos may appear outside the app.</p>
      </details>
    </article>)}</div>{!roots.length && <p className="muted">Nothing written here yet.</p>}
    <h2>Your projects</h2>{data.projects.map(p => <article className="project-row" key={p.id}><div><h3>{p.title}</h3><p>{p.status}{p.deadline ? ` / ${p.deadline}` : ''}</p></div><button onClick={() => setEditing(p)}>Edit project</button></article>)}
    {editing && <form className="entry-form" onSubmit={e => { e.preventDefault(); const p = editing; act(async () => { await product.update('projects', p.id, { title: p.title, description: p.description, notes: p.notes, status: p.status, priority: p.priority, ...(p.deadline ? { deadline: p.deadline } : {}), ...(p.estimatedMinutes !== undefined ? { estimatedMinutes: p.estimatedMinutes } : {}) }); setEditing(null); }); }}><h2>Edit project</h2><label>Title<input required value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label>Description<textarea value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></label><div className="choices">{(['active', 'paused', 'completed', 'archived'] as const).map(status => <Pill key={status} selected={editing.status === status} onClick={() => setEditing({ ...editing, status })}>{status}</Pill>)}</div><label>Deadline<input type="date" value={editing.deadline ?? ''} onChange={e => setEditing({ ...editing, deadline: e.target.value })} /></label><label>Priority<select value={editing.priority} onChange={e => setEditing({ ...editing, priority: e.target.value as Project['priority'] })}>{['low', 'normal', 'high'].map(p => <option key={p}>{p}</option>)}</select></label><label>Estimated minutes<input min="0" type="number" value={editing.estimatedMinutes ?? ''} onChange={e => setEditing({ ...editing, estimatedMinutes: e.target.value ? Number(e.target.value) : undefined })} /></label><label>Notes<textarea value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></label><button>Save project</button><button type="button" onClick={() => setEditing(null)}>Cancel</button><button type="button" onClick={() => { if (confirm('Remove this project? Tasks and recorded time stay.')) act(async () => { await product.remove('projects', editing.id); setEditing(null); }); }}>Remove project</button></form>}
  </section>;
}
export function AddChecklistItem({ parent, life, act }: { parent: Task; life: LifeService; act: (f: () => Promise<unknown>) => void }) {
  const [open, setOpen] = useState(false); const [text, setText] = useState('');
  return <div className="memo-add">{open ? <form onSubmit={e => { e.preventDefault(); act(async () => { await life.addTask(text, { parentTaskId: parent.id, ...(parent.projectId ? { projectId: parent.projectId } : {}) }); setText(''); }); }}><input aria-label={`New item for ${parent.title}`} required value={text} onChange={e => setText(e.target.value)} maxLength={140} autoFocus /><AddButton label={`Save item for ${parent.title}`} type="submit" /><button type="button" onClick={() => setOpen(false)}>Close</button></form> : <AddButton label={`Add item to ${parent.title}`} onClick={() => setOpen(true)} />}</div>;
}
