import { useEffect, useState } from 'react';
import { DEFAULT_PREFERENCES, type PreferencesSettings } from '../domain/models';
import type { ProductService } from '../services/productService';
import type { FirebaseIdentity } from '../services/firebaseCloud';
import type { SyncEngine } from '../services/syncEngine';
import { CatCompanion } from './CatCompanion';
import { Pill, Toggle } from './Controls';
export function Onboarding({ product, identity, sync, done }: { product: ProductService; identity: FirebaseIdentity | null; sync: SyncEngine | null; done: () => void }) {
 const [step, setStep] = useState(0); const [settings, setSettings] = useState<PreferencesSettings>(structuredClone(DEFAULT_PREFERENCES)); const [waiting, setWaiting] = useState(false); const [issue, setIssue] = useState('');
 useEffect(() => { if (!sync?.getSnapshot().account) return; let live = true; setWaiting(true); void sync.syncNow().then(async () => { const prefs = await product.preferences(); if (!live) return; if (prefs.onboardingComplete) done(); else { setSettings(prefs); setStep(2); } }).finally(() => { if (live) setWaiting(false); }); return () => { live = false; }; }, [sync, product, done]);
 const emphasis = ['My day', 'Tasks', 'Projects', 'Journaling', 'Food', 'Hydration', 'Mood & body', 'Me time', 'Reminders'];
 return <main className="onboarding"><a className="brand" href="#Today">My Life</a><section className="onboarding-paper"><CatCompanion state="idle" />
 {step === 0 && <><h1>A small place for your actual life.</h1><p>Plan a little. Remember a little. Leave room for living.</p><button className="talk-button" onClick={() => setStep(1)}>Get started</button></>}
 {step === 1 && <><h1>Your private My Life account.</h1><p>Your account connects this notebook across your devices. Journals and health logs stay local unless you choose to sync them.</p><button className="talk-button" disabled={!identity || waiting} onClick={() => { setWaiting(true); setIssue(''); void identity!.signIn().catch(() => setIssue('Sign-in did not finish. You can write on this device and try again later.')).finally(() => setWaiting(false)); }}>Continue with Google</button><button onClick={() => setStep(2)}>Continue on this device</button><p className="small muted">Local use works offline. You can sign in from Settings later.</p></>}
 {step === 2 && <><h1>What should I call you?</h1><label>Preferred name<input autoFocus maxLength={100} value={settings.preferredName} onChange={e => setSettings({ ...settings, preferredName: e.target.value })} placeholder="Your name, if you want" /></label><button onClick={() => setStep(3)}>Next</button></>}
 {step === 3 && <><h1>What would you like a little help with?</h1><div className="choices">{emphasis.map(label => <Pill key={label} selected={settings.emphasis.includes(label)} onClick={() => setSettings({ ...settings, emphasis: settings.emphasis.includes(label) ? settings.emphasis.filter(v => v !== label) : [...settings.emphasis, label] })}>{label}</Pill>)}</div><p className="small muted">This is a starting point. Everything stays available in Settings.</p><button onClick={() => { setSettings(s => ({ ...s, modules: { ...s.modules, food: s.emphasis.includes('Food'), hydration: s.emphasis.includes('Hydration'), meTime: s.emphasis.includes('Me time') } })); setStep(4); }}>Next</button></>}
 {step === 4 && <><h1>Would you like cycle and period tracking?</h1><div className="choices"><Pill selected={settings.modules.cycle} onClick={() => setSettings({ ...settings, modules: { ...settings.modules, cycle: true } })}>Yes, include it</Pill><Pill selected={!settings.modules.cycle} onClick={() => setSettings({ ...settings, modules: { ...settings.modules, cycle: false } })}>Not for me</Pill></div><p className="small muted">You can change this later. No assumptions about you.</p><button onClick={() => setStep(5)}>Next</button></>}
 {step === 5 && <><h1>Any gentle reminders?</h1>{(['water', 'meals', 'morning', 'evening'] as const).map(key => <Toggle key={key} label={{ water: 'Water', meals: 'Meals', morning: 'Morning routine', evening: 'Evening routine' }[key]} checked={settings.routines[key]} onChange={on => setSettings({ ...settings, routines: { ...settings.routines, [key]: on } })} />)}<p className="small muted">These are preferences. Choose reminder times and notification permission when you are ready, in Reminders.</p><button onClick={() => setStep(6)}>Next</button></>}
 {step === 6 && <><h1>That's enough setup.</h1><p>A little room for your day.</p><button className="talk-button" disabled={waiting} onClick={() => { setWaiting(true); void product.savePreferences({ ...settings, onboardingComplete: true }).then(done).catch(() => setIssue('Could not save setup. Your data is preserved. Please try again.')).finally(() => setWaiting(false)); }}>Start My Life</button></>}
 {waiting && <p role="status">Opening your notebook...</p>}{issue && <p role="status">{issue}</p>}{step > 1 && !waiting && <button className="text-link" onClick={() => setStep(step - 1)}>Back</button>}
 </section></main>;
}
